# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_overview = QtWidgets.QWidget()
        self.tab_overview.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tab_overview.setObjectName("tab_overview")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_overview)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.group_accountName = QtWidgets.QGroupBox(self.tab_overview)
        self.group_accountName.setObjectName("group_accountName")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_accountName)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_accountName = QtWidgets.QLabel(self.group_accountName)
        self.label_accountName.setObjectName("label_accountName")
        self.gridLayout_3.addWidget(self.label_accountName, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.group_accountName, 0, 0, 1, 1)
        self.group_total = QtWidgets.QGroupBox(self.tab_overview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_total.sizePolicy().hasHeightForWidth())
        self.group_total.setSizePolicy(sizePolicy)
        self.group_total.setObjectName("group_total")
        self.gridLayout = QtWidgets.QGridLayout(self.group_total)
        self.gridLayout.setObjectName("gridLayout")
        self.label_cashTypeIcon = QtWidgets.QLabel(self.group_total)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cashTypeIcon.sizePolicy().hasHeightForWidth())
        self.label_cashTypeIcon.setSizePolicy(sizePolicy)
        self.label_cashTypeIcon.setObjectName("label_cashTypeIcon")
        self.gridLayout.addWidget(self.label_cashTypeIcon, 0, 1, 1, 1)
        self.label_totalAmount = QtWidgets.QLabel(self.group_total)
        self.label_totalAmount.setObjectName("label_totalAmount")
        self.gridLayout.addWidget(self.label_totalAmount, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.group_total, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_overview, "")
        self.tab_stock = QtWidgets.QWidget()
        self.tab_stock.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tab_stock.setObjectName("tab_stock")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_stock)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_stock = QtWidgets.QTabWidget(self.tab_stock)
        self.tabWidget_stock.setObjectName("tabWidget_stock")
        self.tab_sh_stock = QtWidgets.QWidget()
        self.tab_sh_stock.setObjectName("tab_sh_stock")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_sh_stock)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_sh = QtWidgets.QLabel(self.tab_sh_stock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sh.sizePolicy().hasHeightForWidth())
        self.label_sh.setSizePolicy(sizePolicy)
        self.label_sh.setText("")
        self.label_sh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_sh.setObjectName("label_sh")
        self.gridLayout_5.addWidget(self.label_sh, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 1, 1, 1)
        self.pushButton_sh = QtWidgets.QPushButton(self.tab_sh_stock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sh.sizePolicy().hasHeightForWidth())
        self.pushButton_sh.setSizePolicy(sizePolicy)
        self.pushButton_sh.setObjectName("pushButton_sh")
        self.gridLayout_5.addWidget(self.pushButton_sh, 2, 1, 1, 1)
        self.listWidget_sh = QtWidgets.QListWidget(self.tab_sh_stock)
        self.listWidget_sh.setObjectName("listWidget_sh")
        self.gridLayout_5.addWidget(self.listWidget_sh, 0, 0, 3, 1)
        self.tabWidget_stock.addTab(self.tab_sh_stock, "")
        self.tab_sz_stock = QtWidgets.QWidget()
        self.tab_sz_stock.setObjectName("tab_sz_stock")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_sz_stock)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_sz = QtWidgets.QLabel(self.tab_sz_stock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sz.sizePolicy().hasHeightForWidth())
        self.label_sz.setSizePolicy(sizePolicy)
        self.label_sz.setText("")
        self.label_sz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_sz.setObjectName("label_sz")
        self.gridLayout_6.addWidget(self.label_sz, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(354, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 1, 1, 1)
        self.pushButton_sz = QtWidgets.QPushButton(self.tab_sz_stock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sz.sizePolicy().hasHeightForWidth())
        self.pushButton_sz.setSizePolicy(sizePolicy)
        self.pushButton_sz.setObjectName("pushButton_sz")
        self.gridLayout_6.addWidget(self.pushButton_sz, 2, 1, 1, 1)
        self.listWidget_sz = QtWidgets.QListWidget(self.tab_sz_stock)
        self.listWidget_sz.setObjectName("listWidget_sz")
        self.gridLayout_6.addWidget(self.listWidget_sz, 0, 0, 3, 1)
        self.tabWidget_stock.addTab(self.tab_sz_stock, "")
        self.tab_own_stock = QtWidgets.QWidget()
        self.tab_own_stock.setObjectName("tab_own_stock")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_own_stock)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_own = QtWidgets.QLabel(self.tab_own_stock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_own.sizePolicy().hasHeightForWidth())
        self.label_own.setSizePolicy(sizePolicy)
        self.label_own.setText("")
        self.label_own.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_own.setObjectName("label_own")
        self.gridLayout_8.addWidget(self.label_own, 0, 1, 1, 1)
        self.pushButton_own = QtWidgets.QPushButton(self.tab_own_stock)
        self.pushButton_own.setObjectName("pushButton_own")
        self.gridLayout_8.addWidget(self.pushButton_own, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 1, 1, 1, 1)
        self.listWidget_own = QtWidgets.QListWidget(self.tab_own_stock)
        self.listWidget_own.setObjectName("listWidget_own")
        self.gridLayout_8.addWidget(self.listWidget_own, 0, 0, 3, 1)
        self.tabWidget_stock.addTab(self.tab_own_stock, "")
        self.gridLayout_4.addWidget(self.tabWidget_stock, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_stock, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.menubar.setObjectName("menubar")
        self.menu_game = QtWidgets.QMenu(self.menubar)
        self.menu_game.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.menu_game.setObjectName("menu_game")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.menu_edit.setObjectName("menu_edit")
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.menu_view.setObjectName("menu_view")
        self.menu_tool = QtWidgets.QMenu(self.menubar)
        self.menu_tool.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.menu_tool.setObjectName("menu_tool")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_start = QtWidgets.QAction(MainWindow)
        self.action_start.setObjectName("action_start")
        self.action_logout = QtWidgets.QAction(MainWindow)
        self.action_logout.setObjectName("action_logout")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_refresh = QtWidgets.QAction(MainWindow)
        self.action_refresh.setObjectName("action_refresh")
        self.action_settings = QtWidgets.QAction(MainWindow)
        self.action_settings.setObjectName("action_settings")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_tutorial = QtWidgets.QAction(MainWindow)
        self.action_tutorial.setObjectName("action_tutorial")
        self.action_update = QtWidgets.QAction(MainWindow)
        self.action_update.setObjectName("action_update")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menu_game.addAction(self.action_start)
        self.menu_game.addSeparator()
        self.menu_game.addAction(self.action_logout)
        self.menu_game.addSeparator()
        self.menu_game.addAction(self.action_exit)
        self.menu_edit.addAction(self.action_refresh)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_settings)
        self.menu_help.addAction(self.action_help)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_tutorial)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_update)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_game.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_tool.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_stock.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Real Stock War"))
        self.group_accountName.setTitle(_translate("MainWindow", "账户名"))
        self.label_accountName.setText(_translate("MainWindow", "TextLabel"))
        self.group_total.setTitle(_translate("MainWindow", "总资产"))
        self.label_cashTypeIcon.setText(_translate("MainWindow", "￥"))
        self.label_totalAmount.setText(_translate("MainWindow", "233"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_overview), _translate("MainWindow", "总览"))
        self.pushButton_sh.setText(_translate("MainWindow", "买入"))
        self.listWidget_sh.setSortingEnabled(True)
        self.tabWidget_stock.setTabText(self.tabWidget_stock.indexOf(self.tab_sh_stock), _translate("MainWindow", "上海"))
        self.pushButton_sz.setText(_translate("MainWindow", "买入"))
        self.listWidget_sz.setSortingEnabled(True)
        self.tabWidget_stock.setTabText(self.tabWidget_stock.indexOf(self.tab_sz_stock), _translate("MainWindow", "深圳"))
        self.pushButton_own.setText(_translate("MainWindow", "卖出"))
        self.tabWidget_stock.setTabText(self.tabWidget_stock.indexOf(self.tab_own_stock), _translate("MainWindow", "持有"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stock), _translate("MainWindow", "股票"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "基金"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "期货"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "外汇"))
        self.menu_game.setTitle(_translate("MainWindow", "游戏"))
        self.menu_edit.setTitle(_translate("MainWindow", "编辑"))
        self.menu_view.setTitle(_translate("MainWindow", "视图"))
        self.menu_tool.setTitle(_translate("MainWindow", "工具"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.action_start.setText(_translate("MainWindow", "开始新游戏"))
        self.action_logout.setText(_translate("MainWindow", "注销账号"))
        self.action_exit.setText(_translate("MainWindow", "退出游戏"))
        self.action_refresh.setText(_translate("MainWindow", "刷新"))
        self.action_settings.setText(_translate("MainWindow", "游戏设置"))
        self.action_help.setText(_translate("MainWindow", "帮助文档"))
        self.action_tutorial.setText(_translate("MainWindow", "新手教程"))
        self.action_update.setText(_translate("MainWindow", "检查更新"))
        self.action_about.setText(_translate("MainWindow", "关于"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

