# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SellStock.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SellStock(object):
    def setupUi(self, SellStock):
        SellStock.setObjectName("SellStock")
        SellStock.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SellStock.sizePolicy().hasHeightForWidth())
        SellStock.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(SellStock)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_stock_info = QtWidgets.QGroupBox(SellStock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_stock_info.sizePolicy().hasHeightForWidth())
        self.groupBox_stock_info.setSizePolicy(sizePolicy)
        self.groupBox_stock_info.setObjectName("groupBox_stock_info")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_stock_info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_stock_info = QtWidgets.QLabel(self.groupBox_stock_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stock_info.sizePolicy().hasHeightForWidth())
        self.label_stock_info.setSizePolicy(sizePolicy)
        self.label_stock_info.setText("")
        self.label_stock_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_stock_info.setObjectName("label_stock_info")
        self.gridLayout_2.addWidget(self.label_stock_info, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_stock_info, 0, 0, 2, 1)
        self.label_prefix = QtWidgets.QLabel(SellStock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_prefix.sizePolicy().hasHeightForWidth())
        self.label_prefix.setSizePolicy(sizePolicy)
        self.label_prefix.setObjectName("label_prefix")
        self.gridLayout.addWidget(self.label_prefix, 1, 1, 1, 1)
        self.spinBox_sell_amount = QtWidgets.QSpinBox(SellStock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_sell_amount.sizePolicy().hasHeightForWidth())
        self.spinBox_sell_amount.setSizePolicy(sizePolicy)
        self.spinBox_sell_amount.setSuffix("")
        self.spinBox_sell_amount.setMaximum(999999999)
        self.spinBox_sell_amount.setObjectName("spinBox_sell_amount")
        self.gridLayout.addWidget(self.spinBox_sell_amount, 1, 2, 1, 1)
        self.label_fix = QtWidgets.QLabel(SellStock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fix.sizePolicy().hasHeightForWidth())
        self.label_fix.setSizePolicy(sizePolicy)
        self.label_fix.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_fix.setObjectName("label_fix")
        self.gridLayout.addWidget(self.label_fix, 1, 3, 1, 1)
        self.pushButton_sell = QtWidgets.QPushButton(SellStock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sell.sizePolicy().hasHeightForWidth())
        self.pushButton_sell.setSizePolicy(sizePolicy)
        self.pushButton_sell.setObjectName("pushButton_sell")
        self.gridLayout.addWidget(self.pushButton_sell, 2, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(SellStock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 2, 1, 1, 3)
        self.groupBox_account_info = QtWidgets.QGroupBox(SellStock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_account_info.sizePolicy().hasHeightForWidth())
        self.groupBox_account_info.setSizePolicy(sizePolicy)
        self.groupBox_account_info.setObjectName("groupBox_account_info")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_account_info)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_account_info = QtWidgets.QLabel(self.groupBox_account_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_account_info.sizePolicy().hasHeightForWidth())
        self.label_account_info.setSizePolicy(sizePolicy)
        self.label_account_info.setText("")
        self.label_account_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_account_info.setObjectName("label_account_info")
        self.gridLayout_3.addWidget(self.label_account_info, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_account_info, 0, 1, 1, 3)

        self.retranslateUi(SellStock)
        QtCore.QMetaObject.connectSlotsByName(SellStock)

    def retranslateUi(self, SellStock):
        _translate = QtCore.QCoreApplication.translate
        SellStock.setWindowTitle(_translate("SellStock", "卖出信息"))
        self.groupBox_stock_info.setTitle(_translate("SellStock", "股票信息"))
        self.label_prefix.setText(_translate("SellStock", "卖出："))
        self.label_fix.setText(_translate("SellStock", "支"))
        self.pushButton_sell.setText(_translate("SellStock", "卖出"))
        self.pushButton_cancel.setText(_translate("SellStock", "取消"))
        self.groupBox_account_info.setTitle(_translate("SellStock", "账户信息"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SellStock = QtWidgets.QWidget()
    ui = Ui_SellStock()
    ui.setupUi(SellStock)
    SellStock.show()
    sys.exit(app.exec_())

